# docker-compose.yml
version: "3.8"
services:
  stable_diffusion:
    build: ./app
    container_name: stable-diffusion
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ./app/resources:/app/resources
      - ./app/logs:/app/logs
      - ./app/output:/app/output  
      
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
